# Generated by Django 5.2.6 on 2025-09-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d')),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
